-- schema.sql
-- Estructura relacional: equipo (1) -> jugador (N)

DROP TABLE IF EXISTS jugador;
DROP TABLE IF EXISTS equipo;

CREATE TABLE equipo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    ciudad VARCHAR(100) NOT NULL
);

CREATE TABLE jugador (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    posicion VARCHAR(50) NOT NULL,
    dorsal INT,
    equipo_id BIGINT NOT NULL,
    CONSTRAINT fk_jugador_equipo
        FOREIGN KEY (equipo_id)
        REFERENCES equipo(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);
